In [2]:
import numpy as np

a = np.array([1,2,3,5,4,2])
print(a)

[1 2 3 5 4 2]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
d = np.arange(1,13).reshape((3,4))
print(d)
d.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [6]:
e = np.arange(1,18,2)
print(e)

[ 1  3  5  7  9 11 13 15 17]


In [7]:
c.shape

(2, 2, 3)

In [8]:
c.ndim

3

In [9]:
np.arange(48).reshape(2,2,3,4)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

Indexing and slicing

In [10]:
a1 = np.arange(10)
print(a1)
print()
a2 = np.arange(12).reshape(3,4)
print(a2)
print()
a3 = np.arange(8).reshape(2,2,2)
print(a3)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [11]:
a1[5]

5

In [12]:
a2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
a2[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [14]:
a3[1,1,0:]

array([6, 7])

In [15]:
a3[0,1,1]

3

In [16]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [18]:
a4[::2,2]

array([[ 6,  7,  8],
       [24, 25, 26]])

In [19]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[45, 56, 97, 46],
       [18, 11, 75, 52],
       [37, 86, 82, 69],
       [99, 14, 47, 55],
       [15, 77, 87, 16],
       [31, 10, 83, 55]])

In [20]:
a[a%2 != 0]

array([45, 97, 11, 75, 37, 69, 99, 47, 55, 15, 77, 87, 31, 83, 55])